In [1]:
import pandas as pd

In [3]:
df_viagens = pd.read_csv('../data/raw/2023_Viagem.csv',encoding='Windows-1252', sep=';', decimal=',',thousands='.')

In [4]:
df_viagens.shape

(826989, 22)

In [5]:
df_viagens.columns

Index(['Identificador do processo de viagem', 'Número da Proposta (PCDP)',
       'Situação', 'Viagem Urgente', 'Justificativa Urgência Viagem',
       'Código do órgão superior', 'Nome do órgão superior',
       'Código órgão solicitante', 'Nome órgão solicitante', 'CPF viajante',
       'Nome', 'Cargo', 'Função', 'Descrição Função',
       'Período - Data de início', 'Período - Data de fim', 'Destinos',
       'Motivo', 'Valor diárias', 'Valor passagens', 'Valor devolução',
       'Valor outros gastos'],
      dtype='str')

In [7]:
df_viagens.dtypes

Identificador do processo de viagem      int64
Número da Proposta (PCDP)                  str
Situação                                   str
Viagem Urgente                             str
Justificativa Urgência Viagem              str
Código do órgão superior                 int64
Nome do órgão superior                     str
Código órgão solicitante                 int64
Nome órgão solicitante                     str
CPF viajante                               str
Nome                                       str
Cargo                                      str
Função                                     str
Descrição Função                           str
Período - Data de início                   str
Período - Data de fim                      str
Destinos                                   str
Motivo                                     str
Valor diárias                          float64
Valor passagens                        float64
Valor devolução                        float64
Valor outros gastos                    float64
dtype: object

In [8]:
df_viagens.info()

<class 'pandas.DataFrame'>
RangeIndex: 826989 entries, 0 to 826988
Data columns (total 22 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   Identificador do processo de viagem  826989 non-null  int64
 1   Número da Proposta (PCDP)            826989 non-null  str
 2   Situação                             826989 non-null  str
 3   Viagem Urgente                       826989 non-null  str
 4   Justificativa Urgência Viagem        826887 non-null  str
 5   Código do órgão superior             826989 non-null  int64
 6   Nome do órgão superior               826989 non-null  str
 7   Código órgão solicitante             826989 non-null  int64
 8   Nome órgão solicitante               826989 non-null  str
 9   CPF viajante                         748302 non-null  str
 10  Nome                                 826989 non-null  str
 11  Cargo                                505154 non-null  str
 12  Função                               826989 non-null  str
 13  Descrição Função                     826977 non-null  str
 14  Período - Data de início             826989 non-null  str
 15  Período - Data de fim                826989 non-null  str
 16  Destinos                             826989 non-null  str
 17  Motivo                               826989 non-null  str
 18  Valor diárias                        826989 non-null  float64
 19  Valor passagens                      826989 non-null  float64
 20  Valor devolução                      826989 non-null  float64
 21  Valor outros gastos                  826989 non-null  float64
dtypes: float64(4), int64(3), str(15)
memory usage: 138.8 MB

In [10]:
df_viagens.duplicated().sum()

np.int64(0)

In [12]:
df_viagens.columns

Index(['Identificador do processo de viagem', 'Número da Proposta (PCDP)',
       'Situação', 'Viagem Urgente', 'Justificativa Urgência Viagem',
       'Código do órgão superior', 'Nome do órgão superior',
       'Código órgão solicitante', 'Nome órgão solicitante', 'CPF viajante',
       'Nome', 'Cargo', 'Função', 'Descrição Função',
       'Período - Data de início', 'Período - Data de fim', 'Destinos',
       'Motivo', 'Valor diárias', 'Valor passagens', 'Valor devolução',
       'Valor outros gastos'],
      dtype='str')

In [ ]:
df_viagens[[
    'Valor diárias', 
    'Valor passagens', 
    'Valor devolução',
    'Valor outros gastos']].head()

   Valor diárias  Valor passagens  Valor devolução  Valor outros gastos
0           0.00             0.00              0.0                 0.00
1           0.00             0.00              0.0                 0.00
2       39565.70          7434.13              0.0              1095.35
3        1013.96             0.00              0.0                 0.00
4           0.00         14903.10              0.0                 0.00

In [15]:
df_viagens["Despesas"] = df_viagens["Valor diárias"] + df_viagens["Valor passagens"] - df_viagens["Valor devolução"] + df_viagens["Valor outros gastos"]

In [17]:
df_viagens[[
    'Valor diárias', 
    'Valor passagens', 
    'Valor devolução',
    'Valor outros gastos',
    'Despesas'
    ]].head()

,Valor diárias,Valor passagens,Valor devolução,Valor outros gastos,Despesas
0,0.00,0.00,0.0,0.00,0.00
1,0.00,0.00,0.0,0.00,0.00
2,39565.70,7434.13,0.0,1095.35,48095.18
3,1013.96,0.00,0.0,0.00,1013.96
4,0.00,14903.10,0.0,0.00,14903.10

In [24]:
df_viagens[df_viagens['Despesas'] == 0]['Despesas'].value_counts()

Despesas
0.0    44166
Name: count, dtype: int64

In [25]:
df_viagens[df_viagens['Despesas'] < 0]['Despesas'].value_counts()

Despesas
-110.33    1
-150.45    1
-41.66     1
-589.91    1
-50.75     1
-150.45    1
-4.68      1
-0.29      1
Name: count, dtype: int64

Cargo nulo — mantém no dataset; filtra fora só nas perguntas que dependem de Cargo.
Datas como texto — vamos converter agora.
Despesas = 0 — mantém no dataset, sem tratamento.
Despesas < 0 — mantém no dataset (diferente da minha sugestão inicial, mas tudo bem — só 8 linhas, não deve distorcer os resultados agregados de forma perceptível).

In [26]:
df_viagens.columns

Index(['Identificador do processo de viagem', 'Número da Proposta (PCDP)',
       'Situação', 'Viagem Urgente', 'Justificativa Urgência Viagem',
       'Código do órgão superior', 'Nome do órgão superior',
       'Código órgão solicitante', 'Nome órgão solicitante', 'CPF viajante',
       'Nome', 'Cargo', 'Função', 'Descrição Função',
       'Período - Data de início', 'Período - Data de fim', 'Destinos',
       'Motivo', 'Valor diárias', 'Valor passagens', 'Valor devolução',
       'Valor outros gastos', 'Despesas'],
      dtype='str')

In [28]:
df_viagens[[
       'Período - Data de início', 
       'Período - Data de fim'
       ]].head()

  Período - Data de início Período - Data de fim
0               01/01/2023            02/12/2023
1               16/01/2023            28/02/2024
2               10/01/2023            29/01/2023
3               05/02/2023            10/02/2023
4               01/01/2023            07/07/2023

In [29]:
df_viagens[[
       'Período - Data de início', 
       'Período - Data de fim'
       ]].dtypes

Período - Data de início    str
Período - Data de fim       str
dtype: object

In [ ]:
df_viagens['Período - Data de início'] = pd.to_datetime(df_viagens['Período - Data de início'], format='%d/%m/%Y', errors='coerce')
df_viagens['Período - Data de fim'] = pd.to_datetime(df_viagens['Período - Data de fim'], format='%d/%m/%Y', errors='coerce')

In [32]:
df_viagens[[
       'Período - Data de início', 
       'Período - Data de fim'
       ]].dtypes

Período - Data de início    datetime64[us]
Período - Data de fim       datetime64[us]
dtype: object

In [33]:
df_viagens[[
       'Período - Data de início', 
       'Período - Data de fim'
       ]].info()

<class 'pandas.DataFrame'>
RangeIndex: 826989 entries, 0 to 826988
Data columns (total 2 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Período - Data de início  826989 non-null  datetime64[us]
 1   Período - Data de fim     826989 non-null  datetime64[us]
dtypes: datetime64[us](2)
memory usage: 12.6 MB